package com.hsjry.p2p.athena.dal.dao.model;

import java.util.Date;

public class AthenaBizSerialExt extends AthenaBizSerialExtKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_biz_serial_ext.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_biz_serial_ext.parameter
     *
     * @mbg.generated
     */
    private String parameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_biz_serial_ext.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_biz_serial_ext.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_biz_serial_ext.id
     *
     * @return the value of athena_biz_serial_ext.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_biz_serial_ext.id
     *
     * @param id the value for athena_biz_serial_ext.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_biz_serial_ext.parameter
     *
     * @return the value of athena_biz_serial_ext.parameter
     *
     * @mbg.generated
     */
    public String getParameter() {
        return parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_biz_serial_ext.parameter
     *
     * @param parameter the value for athena_biz_serial_ext.parameter
     *
     * @mbg.generated
     */
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_biz_serial_ext.create_time
     *
     * @return the value of athena_biz_serial_ext.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_biz_serial_ext.create_time
     *
     * @param createTime the value for athena_biz_serial_ext.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_biz_serial_ext.update_time
     *
     * @return the value of athena_biz_serial_ext.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_biz_serial_ext.update_time
     *
     * @param updateTime the value for athena_biz_serial_ext.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}