package com.hsjry.p2p.athena.dal.dao.model;

import java.util.Date;

public class AthenaRpcLog extends AthenaRpcLogKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.partner_serial_no
     *
     * @mbg.generated
     */
    private String partnerSerialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.out_serial_no
     *
     * @mbg.generated
     */
    private String outSerialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.request
     *
     * @mbg.generated
     */
    private String request;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.response
     *
     * @mbg.generated
     */
    private String response;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.biz_type
     *
     * @mbg.generated
     */
    private String bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.deal_time
     *
     * @mbg.generated
     */
    private Long dealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.partner_serial_no
     *
     * @return the value of athena_rpc_log.partner_serial_no
     *
     * @mbg.generated
     */
    public String getPartnerSerialNo() {
        return partnerSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.partner_serial_no
     *
     * @param partnerSerialNo the value for athena_rpc_log.partner_serial_no
     *
     * @mbg.generated
     */
    public void setPartnerSerialNo(String partnerSerialNo) {
        this.partnerSerialNo = partnerSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.out_serial_no
     *
     * @return the value of athena_rpc_log.out_serial_no
     *
     * @mbg.generated
     */
    public String getOutSerialNo() {
        return outSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.out_serial_no
     *
     * @param outSerialNo the value for athena_rpc_log.out_serial_no
     *
     * @mbg.generated
     */
    public void setOutSerialNo(String outSerialNo) {
        this.outSerialNo = outSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.request
     *
     * @return the value of athena_rpc_log.request
     *
     * @mbg.generated
     */
    public String getRequest() {
        return request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.request
     *
     * @param request the value for athena_rpc_log.request
     *
     * @mbg.generated
     */
    public void setRequest(String request) {
        this.request = request;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.response
     *
     * @return the value of athena_rpc_log.response
     *
     * @mbg.generated
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.response
     *
     * @param response the value for athena_rpc_log.response
     *
     * @mbg.generated
     */
    public void setResponse(String response) {
        this.response = response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.biz_type
     *
     * @return the value of athena_rpc_log.biz_type
     *
     * @mbg.generated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.biz_type
     *
     * @param bizType the value for athena_rpc_log.biz_type
     *
     * @mbg.generated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.status
     *
     * @return the value of athena_rpc_log.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.status
     *
     * @param status the value for athena_rpc_log.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.deal_time
     *
     * @return the value of athena_rpc_log.deal_time
     *
     * @mbg.generated
     */
    public Long getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.deal_time
     *
     * @param dealTime the value for athena_rpc_log.deal_time
     *
     * @mbg.generated
     */
    public void setDealTime(Long dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.create_time
     *
     * @return the value of athena_rpc_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.create_time
     *
     * @param createTime the value for athena_rpc_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.update_time
     *
     * @return the value of athena_rpc_log.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.update_time
     *
     * @param updateTime the value for athena_rpc_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}