package com.hsjry.p2p.athena.dal.dao.model;

public class AthenaRpcLogKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.partner_id
     *
     * @mbg.generated
     */
    private String partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_rpc_log.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.partner_id
     *
     * @return the value of athena_rpc_log.partner_id
     *
     * @mbg.generated
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.partner_id
     *
     * @param partnerId the value for athena_rpc_log.partner_id
     *
     * @mbg.generated
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_rpc_log.id
     *
     * @return the value of athena_rpc_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_rpc_log.id
     *
     * @param id the value for athena_rpc_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }
}