package com.hsjry.p2p.athena.dal.dao.model;

import java.util.Date;

public class AthenaConfigPartnerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.partner_id
     *
     * @mbg.generated
     */
    private String partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.partner_code
     *
     * @mbg.generated
     */
    private String partnerCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.partner_name
     *
     * @mbg.generated
     */
    private String partnerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.bank_code
     *
     * @mbg.generated
     */
    private String bankCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.bank_name
     *
     * @mbg.generated
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.biz_date
     *
     * @mbg.generated
     */
    private Date bizDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.cut_time
     *
     * @mbg.generated
     */
    private Date cutTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_config_partner_info.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.id
     *
     * @return the value of athena_config_partner_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.id
     *
     * @param id the value for athena_config_partner_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.partner_id
     *
     * @return the value of athena_config_partner_info.partner_id
     *
     * @mbg.generated
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.partner_id
     *
     * @param partnerId the value for athena_config_partner_info.partner_id
     *
     * @mbg.generated
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.partner_code
     *
     * @return the value of athena_config_partner_info.partner_code
     *
     * @mbg.generated
     */
    public String getPartnerCode() {
        return partnerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.partner_code
     *
     * @param partnerCode the value for athena_config_partner_info.partner_code
     *
     * @mbg.generated
     */
    public void setPartnerCode(String partnerCode) {
        this.partnerCode = partnerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.partner_name
     *
     * @return the value of athena_config_partner_info.partner_name
     *
     * @mbg.generated
     */
    public String getPartnerName() {
        return partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.partner_name
     *
     * @param partnerName the value for athena_config_partner_info.partner_name
     *
     * @mbg.generated
     */
    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.bank_code
     *
     * @return the value of athena_config_partner_info.bank_code
     *
     * @mbg.generated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.bank_code
     *
     * @param bankCode the value for athena_config_partner_info.bank_code
     *
     * @mbg.generated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.bank_name
     *
     * @return the value of athena_config_partner_info.bank_name
     *
     * @mbg.generated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.bank_name
     *
     * @param bankName the value for athena_config_partner_info.bank_name
     *
     * @mbg.generated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.status
     *
     * @return the value of athena_config_partner_info.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.status
     *
     * @param status the value for athena_config_partner_info.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.biz_date
     *
     * @return the value of athena_config_partner_info.biz_date
     *
     * @mbg.generated
     */
    public Date getBizDate() {
        return bizDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.biz_date
     *
     * @param bizDate the value for athena_config_partner_info.biz_date
     *
     * @mbg.generated
     */
    public void setBizDate(Date bizDate) {
        this.bizDate = bizDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.cut_time
     *
     * @return the value of athena_config_partner_info.cut_time
     *
     * @mbg.generated
     */
    public Date getCutTime() {
        return cutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.cut_time
     *
     * @param cutTime the value for athena_config_partner_info.cut_time
     *
     * @mbg.generated
     */
    public void setCutTime(Date cutTime) {
        this.cutTime = cutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.create_time
     *
     * @return the value of athena_config_partner_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.create_time
     *
     * @param createTime the value for athena_config_partner_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_config_partner_info.update_time
     *
     * @return the value of athena_config_partner_info.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_config_partner_info.update_time
     *
     * @param updateTime the value for athena_config_partner_info.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}