package com.hsjry.p2p.athena.dal.dao.model;

public class AthenaBizSerialKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_biz_serial.partner_id
     *
     * @mbg.generated
     */
    private String partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column athena_biz_serial.partner_serial_no
     *
     * @mbg.generated
     */
    private String partnerSerialNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_biz_serial.partner_id
     *
     * @return the value of athena_biz_serial.partner_id
     *
     * @mbg.generated
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_biz_serial.partner_id
     *
     * @param partnerId the value for athena_biz_serial.partner_id
     *
     * @mbg.generated
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column athena_biz_serial.partner_serial_no
     *
     * @return the value of athena_biz_serial.partner_serial_no
     *
     * @mbg.generated
     */
    public String getPartnerSerialNo() {
        return partnerSerialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column athena_biz_serial.partner_serial_no
     *
     * @param partnerSerialNo the value for athena_biz_serial.partner_serial_no
     *
     * @mbg.generated
     */
    public void setPartnerSerialNo(String partnerSerialNo) {
        this.partnerSerialNo = partnerSerialNo;
    }
}