package com.hsjry.p2p.athena.dal.dao.service;

import com.hsjry.p2p.athena.dal.dao.model.AthenaRpcLog;
import com.hsjry.p2p.athena.dal.dao.model.AthenaRpcLogExample;
import com.hsjry.p2p.athena.dal.dao.model.AthenaRpcLogKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AthenaRpcLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    long countByExample(AthenaRpcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    int deleteByExample(AthenaRpcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(AthenaRpcLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    int insert(AthenaRpcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    int insertSelective(AthenaRpcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    List<AthenaRpcLog> selectByExample(AthenaRpcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    AthenaRpcLog selectByPrimaryKey(AthenaRpcLogKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AthenaRpcLog record, @Param("example") AthenaRpcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AthenaRpcLog record, @Param("example") AthenaRpcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AthenaRpcLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_rpc_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AthenaRpcLog record);
}