package com.hsjry.p2p.athena.dal.dao.service;

import com.hsjry.p2p.athena.dal.dao.model.AthenaBizSerialExt;
import com.hsjry.p2p.athena.dal.dao.model.AthenaBizSerialExtExample;
import com.hsjry.p2p.athena.dal.dao.model.AthenaBizSerialExtKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AthenaBizSerialExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    long countByExample(AthenaBizSerialExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    int deleteByExample(AthenaBizSerialExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(AthenaBizSerialExtKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    int insert(AthenaBizSerialExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    int insertSelective(AthenaBizSerialExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    List<AthenaBizSerialExt> selectByExample(AthenaBizSerialExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    AthenaBizSerialExt selectByPrimaryKey(AthenaBizSerialExtKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AthenaBizSerialExt record, @Param("example") AthenaBizSerialExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AthenaBizSerialExt record, @Param("example") AthenaBizSerialExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AthenaBizSerialExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial_ext
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AthenaBizSerialExt record);
}