package com.hsjry.p2p.athena.dal.dao.service;

import com.hsjry.p2p.athena.dal.dao.model.AthenaBizSerial;
import com.hsjry.p2p.athena.dal.dao.model.AthenaBizSerialExample;
import com.hsjry.p2p.athena.dal.dao.model.AthenaBizSerialKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AthenaBizSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    long countByExample(AthenaBizSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    int deleteByExample(AthenaBizSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(AthenaBizSerialKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    int insert(AthenaBizSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    int insertSelective(AthenaBizSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    List<AthenaBizSerial> selectByExample(AthenaBizSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    AthenaBizSerial selectByPrimaryKey(AthenaBizSerialKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AthenaBizSerial record, @Param("example") AthenaBizSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AthenaBizSerial record, @Param("example") AthenaBizSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AthenaBizSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_biz_serial
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AthenaBizSerial record);
}