package com.hsjry.p2p.athena.dal.dao.service;

import com.hsjry.p2p.athena.dal.dao.model.AthenaConfigPartnerInfo;
import com.hsjry.p2p.athena.dal.dao.model.AthenaConfigPartnerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AthenaConfigPartnerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    long countByExample(AthenaConfigPartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    int deleteByExample(AthenaConfigPartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    int insert(AthenaConfigPartnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    int insertSelective(AthenaConfigPartnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    List<AthenaConfigPartnerInfo> selectByExample(AthenaConfigPartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    AthenaConfigPartnerInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AthenaConfigPartnerInfo record, @Param("example") AthenaConfigPartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AthenaConfigPartnerInfo record, @Param("example") AthenaConfigPartnerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AthenaConfigPartnerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table athena_config_partner_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AthenaConfigPartnerInfo record);
}